base:
  workdir: ../..
  logging_level: INFO

data:
  
  raw_data: data/hour.csv
  target_col: cnt
  prediction_col: prediction
  numerical_features: ['temp', 'atemp', 'hum', 'windspeed', 'hr', 'weekday']
  categorical_features: ['season', 'holiday', 'workingday']

  reference_data: data/reference.csv
  current_data: data/current.csv

extract_data:
  ref_dates_range: '2011-01-01--2011-01-28'
  cur_dates_range: '2011-01-29--2011-02-28'

train:
  n_estimators: 50
  model_path: models/model.pickle
  
