base:
  reports_dir: reports/train
  logging_level: INFO

data:
  raw_data: data/hour.csv
  train_data: data/train.csv
  test_data: data/test.csv
  reference_data: data/reference_data.csv
  
  target_col: cnt
  prediction_col: prediction
  numerical_features: ['temp', 'atemp', 'hum', 'windspeed', 'hr', 'weekday']
  categorical_features: ['season', 'holiday', 'workingday']

extract_data:
  train_dates_range: '2011-01-01--2011-01-28'
  test_dates_range: '2011-01-29--2011-02-28'

train:
  n_estimators: 45
  model_path: models/model.joblib

evaluate:
  model_performance_path: model_performance.html
  metrics_path: metrics.json

  
