base:
  workdir: ../..
  logging_level: INFO

data:
  
  target_col: cnt
  prediction_col: prediction
  numerical_features: ['temp', 'atemp', 'hum', 'windspeed', 'hr', 'weekday']
  categorical_features: ['season', 'holiday', 'workingday']

  reference_data: data/reference.csv
  current_data: data/current.csv

  reference_prediction: data/reference_prediction.csv
  current_prediction: data/current_prediction.csv

predict:
  model_path: models/model.pickle

monitoring:
  reports_dir: reports
  week_start: '2011-01-29'
  week_end: '2011-02-04'
  model_performance:
    dir_name: model_performance
    quality_metric: quality_metric.html
    predicted_vs_actual: predicted_vs_actual.html
    errors: errors.html
  target_drift: target_drift.html
  data_drift: data_drift.html
  data_quality:
    dir_name: data_quality
    data_summary: data_summary.html
    column_summary: column_summary.html
    data_correlation: data_correlation.html
    missing_values: missing_values.html

  
