stages:
  
  predict:
    vars:
      - PIPELINE_DIR: pipelines/predict
    cmd: python src/stages/predict.py --config=${PIPELINE_DIR}/params.yaml
    # cmd: python ${base.workdir}/src/stages/predict.py --config=params.yaml
    wdir: ../..
    params:
      - ${PIPELINE_DIR}/params.yaml:
        - base
        - predict
    deps:
      - src/stages/predict.py
      - ${predict.model_path}
    outs:
      - ${predict.predictions_dir}/${predict.week_start}--${predict.week_end}.csv